---
title: thorest_thor_fees
---
classDiagram
    namespace thorest {
        class ThorRequest {
            <<interface>>
        }
    }
    namespace thorest_errors {
        class ThorError
    }
    class GetPeersResponse {
        GetPeersResponseJSON toJSON()
    }
    class PeerStat {
        string name
        Hex bestBlockID
        number totalScore
        Hex peerID
        NetAddr netAddr
        boolean inbound
        number duration
        PeerStatJSON toJSON()
    }
    class RetrieveConnectedPeers {
        RetrieveConnectedPeers of()$
        ThorResponse~RetrieveConnectedPeers, GetPeersResponse~ askTo(HttpClient httpClient)
    }
    GetPeersResponse --|> PeerStat
    ThorRequest <|.. RetrieveConnectedPeers
    RetrieveConnectedPeers "askTo" --> GetPeersResponse
    ThorError <-- "throws" ThorRequest
