/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
    preset: 'ts-jest',
    testEnvironment: '../../customEnv.js',
    setupFiles: ['./jest.browser-setup.js'],
    coverageReporters: ['html', 'lcov', 'json'],
    moduleNameMapper: {
        '^@common/(.*)$': '<rootDir>/src/common/$1',
        '^@common$': '<rootDir>/src/common',
        '^@thor/(.*)$': '<rootDir>/src/thor/$1',
        '^@thor$': '<rootDir>/src/thor',
        '^@viem/(.*)$': '<rootDir>/src/viem/$1',
        '^@viem$': '<rootDir>/src/viem',
    },
    runner: 'groups',
    reporters: ['default', 'jest-junit'],
    workerThreads: true,
    modulePaths: ['<rootDir>/src'],
    moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
        '^@certificate$': '<rootDir>/src/certificate',
        '^@certificate/(.*)$': '<rootDir>/src/certificate/$1',
        '^@clients': '<rootDir>/src/clients',
        '^@errors$': '<rootDir>/src/errors',
        '^@errors/(.*)$': '<rootDir>/src/errors/$1',
        '^@hdkey$': '<rootDir>/src/hdkey',
        '^@hdkey/(.*)$': '<rootDir>/src/hdkey/$1',
        '^@keystore$': '<rootDir>/src/keystore',
        '^@keystore/(.*)$': '<rootDir>/src/keystore/$1',
        '^@secp256k1$': '<rootDir>/src/secp256k1',
        '^@secp256k1/(.*)$': '<rootDir>/src/secp256k1/$1',
        '^@transaction$': '<rootDir>/src/transaction',
        '^@transaction/(.*)$': '<rootDir>/src/transaction/$1',
        '^@utils$': '<rootDir>/src/utils',
        '^@utils/(.*)$': '<rootDir>/src/utils/$1',
        '^@vcdm$': '<rootDir>/src/vcdm',
        '^@vcdm/(.*)$': '<rootDir>/src/vcdm/$1',
        '@thor/(.*)': '<rootDir>/src/thor/$1',
        '@thor': '<rootDir>/src/thor',
        '@ws/(.*)': '<rootDir>/src/ws/$1',
        '@ws': '<rootDir>/src/ws',
        '@http/(.*)': '<rootDir>/src/http/$1',
        '@http': '<rootDir>/src/http',
        '^@index$': '<rootDir>/src/index'
    }
};
