import { type Address, type Hex } from '@common/vcdm';
import { TransactionReceiptOutput } from '@thor/thor-client/model/transactions';
import { type TxWithReceipt } from '@thor/thorest/transactions/model';
import { type OutputResponse } from '@thor/thorest/common';
import { BaseTransaction } from '@thor/thor-client/model/transactions/BaseTransaction';

/**
 * A transaction contained in an expanded block.
 *
 * This class extends {@link BaseTransaction} and includes transaction execution results
 * (receipt outputs) that are available when transactions are retrieved as part of a block.
 *
 * Unlike {@link Transaction}, this class includes the transaction outputs/receipt information
 * inline, making it suitable for block-level queries where you need both transaction
 * details and execution results in a single object.
 */
class BlockTransaction extends BaseTransaction {
    /**
     * The transaction identifier (hash).
     */
    readonly id: Hex;

    /**
     * The transaction type
     */
    readonly type: number | null;

    /**
     * The address of the origin account that initiated the transaction.
     */
    readonly origin: Address;

    /**
     * The address of the sponsor / delegator account (VIP-191).
     * null if the transaction is not sponsored.
     */
    readonly delegator: Address | null;

    /**
     * Byte size of the transaction that is RLP encoded.
     */
    readonly size: number;

    /**
     * The outputs generated by executing this transaction.
     * Each output corresponds to a clause in the transaction.
     */
    readonly outputs: TransactionReceiptOutput[];

    /**
     * Constructs a new instance of the class from the thorest response.
     *
     * @param {TxWithReceipt} tx - The transaction with receipt to construct the instance from.
     */
    private constructor(tx: TxWithReceipt) {
        // Call parent constructor with base transaction fields
        super({
            chainTag: tx.chainTag,
            blockRef: tx.blockRef,
            expiration: tx.expiration,
            clauses: tx.clauses,
            gas: tx.gas,
            gasPriceCoef: tx.gasPriceCoef ?? undefined,
            maxFeePerGas: tx.maxFeePerGas ?? undefined,
            maxPriorityFeePerGas: tx.maxPriorityFeePerGas ?? undefined,
            dependsOn: tx.dependsOn,
            nonce: tx.nonce
        });

        // Initialize BlockTransaction-specific fields
        this.id = tx.id;
        this.type = tx.type;
        this.origin = tx.origin;
        this.delegator = tx.delegator;
        this.size = tx.size;
        this.outputs = tx.outputs.map((output: OutputResponse) =>
            TransactionReceiptOutput.of(output)
        );
    }

    /**
     * Creates a new instance of the class from the thorest response.
     *
     * @param {TxWithReceipt} tx - The transaction with receipt to construct the instance from.
     * @returns {BlockTransaction} A new instance of the class.
     */
    static fromThorest(tx: TxWithReceipt): BlockTransaction {
        return new BlockTransaction(tx);
    }
}

export { BlockTransaction };
