/**
 * In the VechainThor blockchain, a certificate is a data structure used for client-side self-signed certificates.
 * It plays a crucial role in providing a mechanism for secure identification and validation of data.
 *
 * Certificates are primarily used for purposes like attestation, validation, and verification of data authenticity.
 * They are used as proofs of authenticity and origin for data exchanged within the vechain ecosystem.
 *
 * @field purpose - The purpose field indicates the intended use or context of the certificate.
 *                  For example, it could be used for identification, verification, or attestation.
 * @field payload - The payload field holds the actual content of the certificate.
 *                  This content can be of various types, such as text, images, or other data.
 * @field domain - The domain field represents the specific context or domain for which the certificate is valid.
 *                 It helps ensure that the certificate is only applicable within the intended context.
 * @field timestamp - The timestamp field records the time at which the certificate was created or issued.
 *                    This provides a temporal reference for the certificate's validity.
 * @field signer - The signer field indicates the address of the entity that signs the certificate.
 *                 It is the public key address of the entity that issues the certificate.
 * @field signature - The signature field contains the cryptographic signature generated by the issuer's private key.
 *                    This signature ensures the integrity and authenticity of the certificate's content.
 */
export interface Certificate {
    purpose: string;
    payload: {
        type: string;
        content: string;
    };
    domain: string;
    timestamp: number;
    signer: string;
    signature?: string;
}

export type { Certificate };
