---
title: thorest_errors
---
classDiagram
    namespace core_errors {
        class VeChainSDKError {
        }
    }
    class ThorError {
        number status
        constructor(string fqn, string message, Record~string, unknown~ args?, Error cause?, number status)
    }
    VeChainSDKError <|-- ThorError
