blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/vechain
    about: Join our Discord community to connect with other VeChain enthusiasts, ask questions, and find answers.
  - name: Telegram
    url: https://t.me/VeChainDevCommunity
    about: Join our Telegram community to connect with other VeChain developers, ask questions, and find answers.