---
title: thorest_http
---
classDiagram
    class FetchHttpClient {
        baseURL: URL
        at(baseURL: url, onRequest(request: Request): Request, onResponse(response: Response): Response, isValid(url: URL): boolean)$ FetchHttpClient
    }
    class HttpClient {
        <<interface>>
        get(httpPath: HttpPath) Promise~Response~
        post(httpPath: HttpPath, httpQuery: HttpQuery, body?: unknown) Promise~Response~
    }
    class HttpPath {
        <<interface>>
        apth: string
    }
    class HttpQuery {
        <<interface>>
        query: string
    }
    HttpClient <|.. FetchHttpClient
