import { type ProviderInternalWalletAccount } from '../types';
import { type SignTransactionOptions } from '../../../../thor-client/transactions/types';
import { type AvailableVeChainProviders, type VeChainSigner } from '../../../../signer/signers/types';
import { AbstractProviderInternalWallet } from '../abstract-wallet/abstract-provider-internal-wallet';
/**
 * Provider internal Base wallet class.
 *
 * This is the most basic wallet implementation we can have:
 * * This wallet is generated by a list of private keys
 */
declare class ProviderInternalBaseWallet extends AbstractProviderInternalWallet {
    /**
     * Get a signer into the internal wallet provider
     * for the given address.
     *
     * @param parentProvider - The parent provider of the Internal Wallet.
     * @param addressOrIndex - Address of the account.
     * @returns The signer for the given address.
     */
    getSigner(parentProvider: AvailableVeChainProviders, addressOrIndex?: string | number): Promise<VeChainSigner | null>;
    /**
     * Get the list of addresses in the wallet.
     *
     * @returns The list of addresses in the wallet.
     */
    getAddresses(): Promise<string[]>;
    /**
     * Get an account given an address or an index.
     *
     * @param addressOrIndex - Address or index of the account.
     * @returns The account with the given address, or null if not found.
     */
    getAccount(addressOrIndex?: string | number): Promise<ProviderInternalWalletAccount | null>;
    /**
     * Get the options for signing a transaction with gasPayer (if any).
     *
     * @returns The options for signing a transaction with gasPayer.
     */
    getGasPayer(): Promise<SignTransactionOptions | null>;
}
export { ProviderInternalBaseWallet };
//# sourceMappingURL=provider-internal-base-wallet.d.ts.map