---
title: thorest_thor_blocks
---
classDiagram
    namespace thorest {
        class ThorRequest {
            <<interface>>
        }
    }
    namespace thorest_errors {
        class ThorError
    }
    class Block {
        UInt number
        BlockId id
        UInt size
        BlockId parentID
        UInt timestamp
        UInt gasLimit
        Address beneficiary
        UInt gasUsed
        HexUInt stringbaseFeePerGas
        UInt totalScore
        TxId txsRoot
        UInt txsFeatures
        TxId stateRoot
        TXId receiptsRoot
        boolean com
        Address signer
        BlockJSON toJSON()
    }
    class RawTx {
        HexUInt raw
        RawTxJSON toJSON()
    }
    class RetrieveBlockError
    class RegularBlockResponse {
        boolean isTrunk
        boolean isFinalized
        TxId[]  transactions
        RegularBlockResponseJSON toJson()
    }
    class RetrieveRawBlock {
        RawTx|null of(Revision revision)$
        ThorRespone~RetrieveRawBlock, TxRaw|null~ astTo(HttpClient httpClient)
    }
    class RetrieveRegularBlock {
        RetrieveRegularBlock|null of(Revision  revision)$
        ThorResponse~RetrieveRegularBlock, RegularBlockResponse|null~ askTo(HttpClient httpClient)
    }
    ThorRequest <|.. RetrieveRawBlock
    ThorRequest <|.. RetrieveRegularBlock
    RegularBlockResponse --|> Block
    RetrieveBlockError --|> ThorError
    RetrieveRawBlock "askTo" --> RawTx
    RetrieveRawBlock "throws" --> RetrieveBlockError
    RetrieveRegularBlock "askTo" --> RegularBlockResponse
    RetrieveRegularBlock  "throws" --> RetrieveBlockError

