---
title: Signer Class Diagram - VIP-191
---
classDiagram
    namespace model {
        class SignedTransactionRequest {
            Uint8Array signature
            SignedTransactionRequestJSON toJSON()
        }
        class TransactionRequest {
            UInt8Array gasPayerSignature
            Uint8Array originSignature
            constructor(TransactionRequestParameter param)
            boolean isDynamicFee()
            boolean isIntendedToBeSponsored()
            boolean isSigned()
            TransactionRequestJSON toJSON()
        }
        class TransactionRequestParam {
            <<interface>>
            Address? beggar
            Hex blockRef
            number chainTag
            Clause[] clauses
            Hex|null dependsOn
            number expiration
            bigint gas
            bigint gasPriceCoef
            bigint? maxFeePerGas
            bigint? maxPriorityFeePerGas
            number nonce
        }
    }
    class Signer {
        Address address
        TrasactionRequest|SignedTransactionRequest sign(TransactionRequest request)
    }
    TransactionRequestParam <|.. TransactionRequest
    TransactionRequest <|-- SignedTransactionRequest
    TransactionRequest <-- "sign(SignedTransactionRequest request)" Signer
    SignedTransactionRequest "sign(SignedTransactionRequest request)" <-- Signer
