---
title: Signer Class Diagram - VIP-191
---
classDiagram
    namespace thor_thor_client_model_transactions {
        class TransactionRequest {
            UInt8Array gasPayerSignature
            Uint8Array originSignature
            Uint8Array signature
            constructor(TransactionRequestParameter param)
            boolean isDynamicFee()
            boolean isIntendedToBeSponsored()
            boolean isSigned()
            TransactionRequestJSON toJSON()
        }
        class TransactionRequestParam {
            <<interface>>
            Address? beggar
            Hex blockRef
            number chainTag
            Clause[] clauses
            Hex|null dependsOn
            number expiration
            bigint gas
            bigint? gasPriceCoef
            bigint? maxFeePerGas
            bigint? maxPriorityFeePerGas
            number nonce
        }
    }
    class Signer {
        Address address
        TrasactionRequest sign(TransactionRequest request)
    }
    class PrivateKeySigner {
        constructor(UInt8Array orivateKey)
        dispose()
    }
    Signer <|-- PrivateKeySigner
    TransactionRequestParam <|.. TransactionRequest
    TransactionRequest <-- "sign(TransactionRequest request)" Signer

