---
title: thorest_thor_model
---
classDiagram
    class Clause {
        Address|null to
        bigint value
        HexUIntL data
        constructor(ClauseJSON: json)
        ClauseJSON toJSON()
    }
    class Event {
        Address address
        HexUInt[] topics
        HexUInt data
        constructor(EventJSON event)
        EventJSON toJSON()
    }
    class Output {
        Address contractAddress
        Event[] events
        Transfer[] transfers
        contructor(OutputJSON json)
        OutputJSON toJSON()
    }
    class Receipt {
        TxId id
        UInt type
        UInt chainTag
        Address origin
        Address delegator
        UInt size
        BlockRef blockRef
        UInt expiration
        Clause[] clauses
        UInt gasPriceCoef
        UInt maxFeePerGas
        UInt maxPriorityFeePerGas
        UInt gas
        TxId dependsOn
        UInt nonce
        UInt gasUsed
        Address gasPayer
        bigint paid
        bigint reward
        boolean reverted
        Output[] outputs
        constructor(ReceiptJSON json)
        ReceiptJSON toJSON()
    }
    class Transfer {
        Address sender
        Address recipient
        UInt amount
        constructor(TransferJSON json)
        TransferJSON toJSON()
    }
