---
title: Transaction refactor
---
classDiagram
    class Clause {
        Address|null to
        bigint value
        Hex|null data
        Txt|null comment
        Hex|null abi
        Clause of(ClauseJSON: json)$
        ClauseJSON toJSON()
    }
    class Codec {
        <<interface>>
        T decode~T~(Uint8Array encoded)
        Uint8Array encode~T~(T obj)
    }
    class RLPCodec {

    }
    class Signer {
        <<interface>>
        Address address
        SignedTransactionRequest sign(TransactionRequest transactionRequest)
        SponsoredTransactionRequest sign(SignedTransactionRequest transactionRequest)
    }
    class SignedTransactionRequest {
        Uint8Array senderSignature
        Uint8Array signature
        SignedTransactionRequest of(SignedTransactionRequestJSON json)$
        SignedTransactionRequestJSON toJSON()
    }
    class SponsoredTransactionRequest {
        Uint8Array gasPayerSignature
    }
    class TransactionRequest {
        Hex blockRef
        number chainTag
        Clause[] clauses
        Hex|null dependsOn
    %% reserved.features
        number|null features
        number expiration
        bigint gas
        bigint gasPriceCoef
        number nonce
    %% reserved.unused
        Uint8Array[]|null reserved
        TransactionRequest of(TxRequestJSON json)$
        TxRequestJSON toJSON()
    }
    RLPCodec --|> Codec
    Clause *-- TransactionRequest
    TransactionRequest <|-- SignedTransactionRequest
    SignedTransactionRequest <|-- SponsoredTransactionRequest
    Signer <-- "1.in Signer.sign(...) " TransactionRequest
    Signer "1.out Signer.sign(...)" --> SignedTransactionRequest
    Signer <-- "2.in Signer.sign(...)" SignedTransactionRequest
    Signer "2.out Signer.sign(...)" --> SponsoredTransactionRequest
    TransactionRequest --> RLPCodec
    SignedTransactionRequest --> RLPCodec
    SponsoredTransactionRequest --> RLPCodec

