---
title: Transaction refactor
---
sequenceDiagram
    actor Signer
    participant TransactionRequest
    participant SignedTransactionRequest
    participant SponsoredTransactionRequest
    TransactionRequest->>Signer: SignedTransactionRequest Signer.sign(TransactionRequest)
    Signer->>SignedTransactionRequest: SignedTransactionRequest Signer.sign(TransactionRequest)
    SignedTransactionRequest->>Signer: SponsoredTransactionRequest Signer.sign(SignedTransactionRequest)
    Signer->>SponsoredTransactionRequest: SponsoredTransactionRequest Signer.sign(SignedTransactionRequest)
