---
title: thorest_thor_model
---
classDiagram
    class GetRawTxResponse {
        HexUInt raw
        TxMeta meta
        constructor(GetRawTxResponseJSON json)
        GetRawTxResponseJSON toJSON()
    }
    class GetTxReceiptResponse {
        ReceiptMeta meta
        constructor(GetTxReceiptResponseJSON json)
        GetTxReceiptResponseJSON toJSON()
    }
    class ReceiptMeta {
        TxId txID
        Address: txOrigin
        constructor(ReceiptMetaJSON json)
        ReceiptMeta toJSON()
    }
    class TxMeta {
        BlockId blockID
        UInt blockNumber
        UInt blockTimestamp
        constructor(TxMetaJSON json)
        TxMetaJSON toJSON()
    }
    Receipt <|-- GetTxReceiptResponse
    TXMeta <|-- ReceiptMeta
