---
title: thorest_thor_model
---
classDiagram
    namespace thor_model {
        class Receipt
    }
    class GetRawTxResponse {
        HexUInt raw
        TxMeta meta
        constructor(GetRawTxResponseJSON json)
        GetRawTxResponseJSON toJSON()
    }
    class GetTxReceiptResponse {
        ReceiptMeta meta
        constructor(GetTxReceiptResponseJSON json)
        GetTxReceiptResponseJSON toJSON()
    }
    Receipt <|-- GetTxReceiptResponse
