permissions:
  contents: read
name: Jobs on tag (manual only)

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag to publish (e.g., 1.2.3)"
                required: true

jobs:
    npm-publish:
        if: false
        uses: ./.github/workflows/publish-sdk.yml
        secrets: inherit
        # Publication intentionally disabled until we create service accounts
