name: Jobs on tag

on:
    workflow_dispatch:

jobs:
    npm-publish:
        uses: ./.github/workflows/publish-sdk.yml
        secrets: inherit

    rpc-proxy-docker-publish:
        uses: ./.github/workflows/rpc-proxy.yml
        secrets: inherit
