name: Qodana Scan

on:
  workflow_call:

jobs:
  sonar-scan:
    name: Qodana Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Qodana Scan # Run Qodana
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_JS }}
        with:
          pr-mode: ${{ github.event_name == 'pull_request' }}
