name: Release Notifications

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  notify:
    name: Slack Notifications for Release
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Notify Slack of release
        if: ${{ env.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ env.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "source": "GitHub",
              "repo": "${{ github.repository }}",
              "tag": "${{ github.event.release.tag_name }}",
              "message": "Release published: ${{ github.event.release.html_url }}"
            }

