name: RPC Proxy - Test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  
            - name: Install & Patch packages
              run: yarn install
            
            - name: Build
              run: yarn build

            - name: Run E2E RPC Proxy tests
              run: |
                yarn workspace @vechain/sdk-rpc-proxy test:e2e
            
            - name: Start Thor solo node
              id: start-solo
              run: yarn start-thor-solo
            
            - name: Start RPC Proxy
              run: |
                yarn workspace @vechain/sdk-rpc-proxy start & disown
            
            - name: Run RPC Proxy tests
              run: |
                yarn test-rpc-proxy
                exit_code=$?
                if [ $exit_code -eq 0 ]; then
                  echo "RPC Proxy tests passed successfully."
                else
                  echo "RPC Proxy tests failed."
                  exit 1
                fi
            
            - name: Stop Thor solo node
              id: stop-solo
              run: yarn stop-thor-solo