name: RPC Proxy

on:
  workflow_dispatch:

jobs:
    test:
      uses: ./.github/workflows/rpc-proxy-test.yml
      secrets: inherit
    
    docker:
      uses: ./.github/workflows/rpc-proxy-docker.yml
      secrets: inherit

