name: RPC Proxy

on:
  pull_request:
    branches:
      - main

jobs:
    test:
      uses: ./.github/workflows/rpc-proxy-test.yml
      secrets: inherit
    
    docker-vulnerability-check:
      uses: ./.github/workflows/rpc-proxy-vulnerability-scan.yml
      secrets: inherit
            
    