name: E2E RPC Proxy test

on:
  workflow_call:

jobs:
  build:
    name: E2E RPC Proxy test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install & Patch packages
        run: yarn install

      - name: Run E2E RPC Proxy tests
        run: |
          yarn workspace @vechain/sdk-rpc-proxy test:e2e